[project]
name = "Ancab"
output_dir = "../build/Ancab"

[inputs]
fasta = "/path/to/Ancistrocladus_abbreviatus_v1.1.reference.fa"
gff = "/path/to/Ancistrocladus_abbreviatus_v1.1.gff"

[sample]
locus_tag = "Ancab"
locus_tag_digits = 6
scientific_name = "Ancistrocladus abbreviatus"
strain = ""
isolate = "Individual I"
geo_loc_name = "Germany"
collection_date = "2020-11-02"
sex = ""
linkage_evidence = "proximity ligation"
genetic_code = "1"

[submission]
datatype = "WGS"
hold_date = "20261224"
bioproject = "PRJDB15740"
biosample = "SAMD00598257"
sra = ["DRR463235"]
keywords = ["WGS", "STANDARD_DRAFT"]

[submitter]
ab_name = ["Doe,J."]
contact = "Jane Doe"
institute = "Institute"
department = "Department"
country = "Japan"
state = "State"
city = "City"
street = "Street Address"
zip = "000-0000"
phone = "00-00-0000-0000"
email = "your.email@example.org"

[reference]
title = "Ancistrocladus abbreviatus genome sequencing"
ab_name = ["Fukushima,K."]
year = 2025
status = "Unpublished"

[st_comment]
tagset_id = "Genome-Assembly-Data"
assembly_method = "hifiasm v. 0.14-r312; HiRise"
assembly_name = "Ancab_1.1"
genome_coverage = "100x"
sequencing_technology = "PacBio Sequel II"

[pipeline]
run_gapjust = true
gap_assembly = "unknown"
infer_complete = true
validate_in_parallel = true
feature_with_gap = "misc_feature"
min_assembly_gap = 50
min_artificial_intron_size = 10
replace_product_patterns = [
  "\\) transport protein",
  "18S rRNA",
  "Ard4p",
  "Arf11p",
  "Arf8p",
  "Atmrk1p",
  "Bce2p",
  "Iaa13p",
  "Iaa20p",
  "Iaa32p",
  "Pglcat2p",
  "Arf17p",
  "Cullin-1",
  "Cullin-3A",
  "Cullin-4",
  "Dnae2p",
  "Gcp2p",
  "Iaa10p",
  "Iaa15p",
  "Iaa2p",
  "Iaa33p",
  "L14B",
  "Lhcb6-1p",
  "Lox4p",
  "Lox9p",
  "Lta2p",
  "MIP05841p",
  "Mlo14p",
  "Rhm1p",
  "Rps7-ap",
  "Sdh2-1p",
  "Sec63",
  "Villin-3",
  "Villin-4",
  "Ycf1p",
  "aci13",
  "cTPxI",
  "trkA",
]

[tools]
java_heap = "16G"
